import "server-only";
import { darajaBaseUrl, darajaAccessToken } from "./daraja";

/**
 * M-Pesa B2C (Business → Customer) payout — how we disburse a held booking to a
 * host's M-Pesa number after check-in. Distinct from STK push (C2B collection).
 *
 * Needs a SEPARATE B2C short code with "Business Payment" enabled, plus an
 * initiator user and that user's pre-encrypted SecurityCredential (generated by
 * encrypting the initiator password against Safaricom's public cert).
 *
 * Config (Vercel):
 *   MPESA_B2C_SHORTCODE        the B2C paybill/short code (PartyA)
 *   MPESA_INITIATOR_NAME       the API initiator username
 *   MPESA_SECURITY_CREDENTIAL  the encrypted initiator password
 * (reuses MPESA_CONSUMER_KEY/SECRET + MPESA_ENV from the collection config.)
 *
 * The request is only an ACKNOWLEDGEMENT — the real result arrives async at the
 * ResultURL, so callers store the ConversationID and settle on the callback.
 */

export function isMpesaB2CConfigured(): boolean {
  return Boolean(
    process.env.MPESA_CONSUMER_KEY &&
      process.env.MPESA_CONSUMER_SECRET &&
      process.env.MPESA_B2C_SHORTCODE &&
      process.env.MPESA_INITIATOR_NAME &&
      process.env.MPESA_SECURITY_CREDENTIAL,
  );
}

export interface B2CParams {
  amount: number; // whole KES
  phone: string; // normalised 2547…
  remarks: string;
  resultUrl: string;
  timeoutUrl: string;
  occasion?: string;
}

export interface B2CResult {
  ok: boolean;
  conversationId?: string;
  originatorConversationId?: string;
  error?: string;
}

export async function b2cPayout(p: B2CParams): Promise<B2CResult> {
  if (!isMpesaB2CConfigured()) return { ok: false, error: "M-Pesa B2C isn't configured." };
  try {
    const token = await darajaAccessToken();
    const res = await fetch(`${darajaBaseUrl()}/mpesa/b2c/v1/paymentrequest`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      cache: "no-store",
      body: JSON.stringify({
        InitiatorName: process.env.MPESA_INITIATOR_NAME,
        SecurityCredential: process.env.MPESA_SECURITY_CREDENTIAL,
        CommandID: "BusinessPayment",
        Amount: Math.round(p.amount),
        PartyA: process.env.MPESA_B2C_SHORTCODE,
        PartyB: p.phone,
        Remarks: p.remarks.slice(0, 100),
        QueueTimeOutURL: p.timeoutUrl,
        ResultURL: p.resultUrl,
        Occasion: (p.occasion ?? "").slice(0, 100),
      }),
    });
    const json = (await res.json().catch(() => ({}))) as {
      ConversationID?: string;
      OriginatorConversationID?: string;
      ResponseCode?: string;
      ResponseDescription?: string;
      errorMessage?: string;
    };
    if (!res.ok || json.ResponseCode !== "0") {
      return { ok: false, error: json.errorMessage ?? json.ResponseDescription ?? `B2C failed (${res.status})` };
    }
    return {
      ok: true,
      conversationId: json.ConversationID,
      originatorConversationId: json.OriginatorConversationID,
    };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : "B2C request failed." };
  }
}
